version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATEBASE: root
      MYSQL_ALLOW_EMPTY_PASSWORD: password
    ports:
      - "3306:3306"

  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/docker
    ports:
      - "3000:3000"
    links:
      - db