default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  host: db

# development環境だけ書き換えてます。
development:
  <<: *default
  username: root
  password: 
  database: docker_development

test:
  <<: *default
  database: docker_test

production:
  <<: *default
  database: docker_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>